name: Main deploy

on:
  workflow_dispatch: 
    inputs:
      build-status:
        description: "Choose the build status for the demo"       
        type: choice
        options:
          - success
          - failure            

jobs:
  call-build:
    uses: ./.github/workflows/o-worflow.yml
    with:
      build-status: ${{inputs.build-status}}   

  deploy:
    runs-on: ubuntu-latest
    needs: call-build
    if: ${{ needs.call-build.outputs.status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploy"

      
